// <auto-generated />
using System;
using DairyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DairyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225185851_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DairyApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Went hiking with Joe",
                            Created = new DateTime(2026, 2, 25, 13, 58, 50, 683, DateTimeKind.Local).AddTicks(3382),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Had a great day with family",
                            Created = new DateTime(2026, 2, 25, 13, 58, 50, 683, DateTimeKind.Local).AddTicks(3583),
                            Title = "Had a great day"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Learned about Entity Framework Core",
                            Created = new DateTime(2026, 2, 25, 13, 58, 50, 683, DateTimeKind.Local).AddTicks(3586),
                            Title = "Learned C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
